/**
 * Tier A — engine model and atmosphere port fidelity.
 *
 * Same contract as the coefficient tests: 1e-12 against the reference, on fixtures
 * generated by running it. Thrust magnitudes are order 10^4, so a relative check is
 * used where absolute error would be meaninglessly loose.
 *
 * Also pins the out-of-table extrapolation, including the regime where it produces
 * negative thrust. That is unphysical, but it is what the model does, and pretending
 * otherwise here would hide it from whoever eventually flies above 50,000 ft.
 */

import { describe, expect, it } from 'vitest'
import golden from '../fixtures/golden-engine.json' with { type: 'json' }
import { airData } from '../src/atmosphere.js'
import {
  THRUST_TABLE_MAX_ALT,
  THRUST_TABLE_MAX_MACH,
  pdot,
  rtau,
  tgear,
  thrust,
  thrustOutsideTable,
} from '../src/aero/engine.js'

const ABS_TOLERANCE = 1e-12
const REL_TOLERANCE = 1e-12

function expectClose(actual: number, expected: number, context: string): void {
  expect(Number.isFinite(actual), `${context}: got ${actual}`).toBe(true)

  const err = Math.abs(actual - expected)
  const scale = Math.max(1, Math.abs(expected))

  expect(
    err / scale,
    `${context}: got ${actual}, want ${expected} (abs err ${err.toExponential(3)})`,
  ).toBeLessThan(Math.max(ABS_TOLERANCE, REL_TOLERANCE))
}

describe('thrust', () => {
  const cases = golden.thrust as Array<{
    in: { power: number; alt: number; mach: number }
    out: { thrust: number }
  }>

  it('matches the reference across the table and beyond it', () => {
    expect(cases.length).toBeGreaterThan(2000)

    for (const c of cases) {
      expectClose(
        thrust(c.in.power, c.in.alt, c.in.mach),
        c.out.thrust,
        `thrust(${c.in.power}, ${c.in.alt}, ${c.in.mach})`,
      )
    }
  })

  it('produces the published sea-level static values', () => {
    // [AEROBENCH] thrust.py, first column of each table. A sanity anchor that does
    // not depend on the fixtures being correct.
    expect(thrust(0, 0, 0)).toBeCloseTo(1060, 6) // idle
    expect(thrust(50, 0, 0)).toBeCloseTo(12680, 6) // military
    expect(thrust(100, 0, 0)).toBeCloseTo(20000, 6) // maximum, afterburner
  })

  it('increases with power at fixed altitude and Mach', () => {
    let prev = -Infinity
    for (let p = 0; p <= 100; p += 5) {
      const t = thrust(p, 10000, 0.6)
      expect(t).toBeGreaterThan(prev)
      prev = t
    }
  })

  it('decreases with altitude at fixed power and Mach', () => {
    let prev = Infinity
    for (let alt = 0; alt <= 50000; alt += 5000) {
      const t = thrust(50, alt, 0.4)
      expect(t).toBeLessThan(prev)
      prev = t
    }
  })
})

describe('thrust outside the tabulated range', () => {
  it('flags altitudes and Mach numbers beyond the data', () => {
    expect(thrustOutsideTable(0, 0)).toBe(false)
    expect(thrustOutsideTable(THRUST_TABLE_MAX_ALT, THRUST_TABLE_MAX_MACH)).toBe(false)
    expect(thrustOutsideTable(THRUST_TABLE_MAX_ALT + 1, 0.5)).toBe(true)
    expect(thrustOutsideTable(20000, THRUST_TABLE_MAX_MACH + 0.01)).toBe(true)
    expect(thrustOutsideTable(-1, 0.5)).toBe(true)
  })

  it('extrapolates rather than clamping, and goes negative high up', () => {
    // Documenting a real limitation rather than papering over it. Full military
    // power at 70,000 ft yields *negative* thrust from linear extrapolation.
    // REQUIREMENTS §2.3 puts the atmosphere ceiling at 60,000 ft; this is why
    // useful flight stops well below that.
    const high = thrust(80, 70000, 0.8)

    expect(thrustOutsideTable(70000, 0.8)).toBe(true)
    expect(high).toBeLessThan(0)

    // At the table edge it is still sane, which bounds where the trouble starts.
    expect(thrust(80, 50000, 0.8)).toBeGreaterThan(0)
  })

  it('treats negative altitude as ~sea level rather than extrapolating downward', () => {
    expect(thrust(50, -100, 0.2)).toBeCloseTo(thrust(50, 0.01, 0.2), 9)
  })
})

describe('throttle gearing', () => {
  const cases = golden.tgear as Array<{ in: { thtl: number }; out: { tgear: number } }>

  it('matches the reference', () => {
    for (const c of cases) {
      expectClose(tgear(c.in.thtl), c.out.tgear, `tgear(${c.in.thtl})`)
    }
  })

  it('has its afterburner detent at 0.77 throttle', () => {
    // Below the detent, throttle covers idle->military. Above it, the curve
    // steepens to cover military->maximum in the remaining travel.
    const belowSlope = (tgear(0.77) - tgear(0.7)) / 0.07
    const aboveSlope = (tgear(0.9) - tgear(0.78)) / 0.12

    expect(aboveSlope).toBeGreaterThan(belowSlope * 3)
    expect(tgear(0)).toBeCloseTo(0, 9)
    expect(tgear(1)).toBeCloseTo(100, 9)
  })

  it('has a small genuine discontinuity at the detent', () => {
    // The two segments do not quite meet: 64.94 * 0.77 = 50.0038, while
    // 217.38 * 0.77 - 117.38 = 50.0026. A step of about 0.0012 power units out of
    // 100, from rounded coefficients in the source.
    //
    // Physically irrelevant — 0.0012% of the power range is far below anything the
    // engine lag can respond to. Pinned rather than asserted away, because "we
    // checked and it is 0.0012" is a different statement from "we assumed it was
    // zero", and only one of them survives someone editing these constants.
    const below = tgear(0.77)
    const above = tgear(0.77 + 1e-9)
    const step = Math.abs(above - below)

    expect(step).toBeGreaterThan(0)
    expect(step).toBeLessThan(0.002)
  })

  it('is monotonic', () => {
    let prev = -Infinity
    for (let t = 0; t <= 1; t += 0.01) {
      const g = tgear(t)
      expect(g).toBeGreaterThan(prev)
      prev = g
    }
  })
})

describe('power level dynamics', () => {
  const cases = golden.powerLag as Array<{
    in: { p3: number; p1: number }
    out: { pdot: number; rtau: number }
  }>

  it('matches the reference for pdot and rtau', () => {
    for (const c of cases) {
      expectClose(pdot(c.in.p3, c.in.p1), c.out.pdot, `pdot(${c.in.p3}, ${c.in.p1})`)
      expectClose(
        rtau(c.in.p1 - c.in.p3),
        c.out.rtau,
        `rtau(${c.in.p1 - c.in.p3})`,
      )
    }
  })

  it('responds slower to large commanded changes than small ones', () => {
    // Spool-up physics: a turbofan asked for a big change takes proportionally
    // longer per unit of change.
    expect(rtau(10)).toBe(1.0)
    expect(rtau(60)).toBe(0.1)
    expect(rtau(35)).toBeLessThan(rtau(10))
    expect(rtau(35)).toBeGreaterThan(rtau(60))
  })

  it('drives power toward the command', () => {
    expect(pdot(30, 40)).toBeGreaterThan(0) // spooling up
    expect(pdot(40, 30)).toBeLessThan(0) // spooling down
    expect(pdot(30, 30)).toBeCloseTo(0, 9) // settled
  })

  it('is asymmetric across the afterburner threshold', () => {
    // Lighting the burner targets 60 before settling; cancelling drops to 40. That
    // asymmetry is why throttle response is not a simple first-order lag.
    const lighting = pdot(49, 51)
    const cancelling = pdot(51, 49)

    expect(lighting).toBeGreaterThan(0)
    expect(cancelling).toBeLessThan(0)
    expect(Math.abs(lighting)).not.toBeCloseTo(Math.abs(cancelling), 3)
  })
})

describe('atmosphere used by the flight model', () => {
  const cases = golden.adc as Array<{
    in: { vt: number; alt: number }
    out: { mach: number; qbar: number }
  }>

  it('matches the reference for Mach and dynamic pressure', () => {
    for (const c of cases) {
      const a = airData(c.in.vt, c.in.alt)
      expectClose(a.mach, c.out.mach, `mach(${c.in.vt}, ${c.in.alt})`)
      expectClose(a.qbar, c.out.qbar, `qbar(${c.in.vt}, ${c.in.alt})`)
    }
  })
})
